### ISSUE TITLE
guix home - have you considered avoiding a single package list?

### ISSUE THREAD

**Issue by moesasji** [abcdw/rde#18]
Having watched your presentations about guix home this looks like a very exciting development that fits better with the rest of guix. Having looked at your source-code it looks like you are making the assumption that the user uses a single list of packages to be installed as a user-environment.

Personally I always dread accidentally triggering a massive update (like compiling Chromium) when I just need one key package updated to get work done. For that reason I wonder whether you have considered splitting the single list of packages into separate ones of related packages? Essentially making the way to manage the installed user packages closer to the manifest model that is this [guix blogpost](https://guix.gnu.org/en/blog/2019/guix-profiles-in-practice/)?

The key benefit for me would be to allow a user to make it easier to only update a subset of packages**.

**this would also make it easier to actually use the ideas in that blogpost, which for new users are tricky.

**Comment by abcdw** [comment]
> Having watched your presentations about guix home this looks like a
> very exciting development that fits better with the rest of
> guix. Having looked at your source-code it looks like you are making
> the assumption that the user uses a single list of packages to be
> installed as a user-environment.

Correct.

> Personally I always dread accidentally triggering a massive update
> (like compiling Chromium) when I just need one key package updated to
> get work done. For that reason I wonder whether you have considered
> splitting the single list of packages into separate ones of related
> packages? Essentially making the way to manage the installed user
> packages closer to the manifest model that is this guix blogpost?

I'm aware of this issue and thought about it briefly.

It's not technically possible to have few home-environments, because
each of them would define the same env variables, run shepherd multiple
times and probably will do some other undesired things. Combining
profiles is an easy task, while combining home-environments is almost
impossible. Imagine having few operating-system declarations work at the
same time on the same machine.

I see the possibility to manage all the configurations for beefy packages
inside home-environment, but install those packages itself with manifest
or any other mechanism. It makes it possible to update subsets of packages
separately, however will decouple configurations from packages, will
make home-environment less reproducible, self-contained and consistent.

I don't think this approach is good, but maybe a way to go.

> Personally I always dread accidentally triggering a massive update
> (like compiling Chromium) when I just need one key package updated to
> get work done.

In most cases when I need to get work done I do not update the system or
user profile. per-project profiles is a different story, but they are
separate from the home-environment anyway. I see the only one
hypothetical and pretty rare case, when it really needed, but for that
inferiors can be used.

> Having watched your presentations about guix home this looks like a
> very exciting development that fits better with the rest of
> guix.

Thank you! BTW, the actual development goes on https://sr.ht/~abcdw,
project mailing lists are here: https://lists.sr.ht/~abcdw, post
question/ideas/patches on respective mailing list, other contributors
and users will be able to participate in the discussion and provide
their feedback and ideas.

-- 
Best regards,
Andrew Tropin

**Comment by moesasji** [comment]
> I'm aware of this issue and thought about it briefly. It's not technically possible to have few home-environments, because each of them would define the same env variables, run shepherd multiple times and probably will do some other undesired things. Combining profiles is an easy task, while combining home-environments is almost impossible.

I was still thinking of this being a single home-environment, but with the ability to have the list of packages that should be in this environment split into multiple if desired. Typical usage would be to update all packages in the user home-environment, but I personally see a use-case for being able to only update a subset. For me pretty much for the same reasons as why it pays of to break up the list into separate manifests. Making this easier to manage/reason about would be on my wish-list as the learning curve is steep....

I'll shut up now and just let you get on with writing code ;)

**Comment by abcdw** [comment]
> I was still thinking of this being a single home-environment, but with
> the ability to have the list of packages that should be in this
> environment split into multiple if desired. Typical usage would be to
> update all packages in the user home-environment, but I personally see a
> use-case for being able to only update a subset. For me pretty much for
> the same reasons as why it pays of to break up the list into separate
> manifests. Making this easier to manage/reason about would be on my
> wish-list as the learning curve is steep....

It's not technically possible to update/build/whatever only the part of
home-environment, as it's not possible to update only first 3 packages
out of 10 of your manifest without splitting it into two different
manifests or using inferiors, but for other technical reasons I
mentioned above it's not possible to have few home-environments (maybe
someday it will change). Thus, the only two options for such feature
are:
- To use a combination of home-environment + manifests, which makes the
whole setup semi-consistent, but gives you freedom to update parts
independently.
- To use inferiors, which is kinda cool, but still in early stages of
development. https://guix.gnu.org/manual/en/guix.html#Inferiors

I keep in mind this use case, but most likely you should rely on two
options above.

> I'll shut up now and just let you get on with writing code ;)

Thank you) We already implemented most of the essential parts, and hope
to make it ready for a wider audience of early adopters soon, just in a
few weeks.

-- 
Best regards,
Andrew Tropin
